config/routes.rb
HtmlScraper::Application.routes.draw do
  root 'home#show'
  
  resources :contents, only: [:create]

end

app/models/content.rb
class Content < ActiveRecord::Base
  validates :href, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def create
    scraper = Scraper.new(params[:content][:href])
    begin
      content = scraper.content.try(:to_s)
    rescue RuntimeError, Errno::ENOENT, Errno::ECONNREFUSED, SocketError => e
      flash[:error] = "Invalid URL"
    else
      Content.create(href: params[:content][:href], content: content)
    end
    redirect_to root_url
  end
  
  protected
  def content_params
    params.require(:content).permit(:href)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @contents = Content.page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/show.html.erb
<div>
  <%= form_for :content, url: contents_path do |f| %>
    <%= f.label 'URL to scrape' %>
    <%= f.text_field :href %>
    <%= f.submit %>
  <% end %>
</div>
<div>
  <table>
    <tr>
      <td>
        Href
      </td>
      <td>
        Content
      </td>
    </tr>
    <% @contents.each do |content| %>
      <tr>
        <td>
          <%= content.href %>
        </td>
        <td>
          <% JSON.parse(content.content).each do |c| %>
            <%= c.html_safe %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= paginate(@contents) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HtmlScraper</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:error] %>
    <div>
      <%= flash[:error] %>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>